### PR TITLE
fix: wrong external repos URL

### PR DESCRIPTION
**Pull request by acasadoquijada**
This commit fixes the URL for the external repositories as specified in #173.

### CODE REVIEW

**Comment by madmas** [comment]
@acasadoquijada thanks a lot for the PR! Due to legal reasons, we need you signoff of the CLA (see  https://dev.karakun.com/cla ), can you do that?

**Comment by acasadoquijada** [comment]
@madmas you are welcome! I sent yesterday the CLA to opensource@karakun.com as mentioned in the link you provided

**Comment by grigala** [comment]
@cla-bot check

**Comment by acasadoquijada** [comment]
Sorry for the delay, just a quick update, I had to resent my CLA. Everything should be fine now

**Comment by sclassen** [comment]
@cla-bot check

**Pull request merged**
